[cosmic-ray]
module-path = "src"
timeout = 5.0
excluded-modules = []
test-command = "pytest"


[cosmic-ray.filters.line-filter.lines]
"math.py" = "1-4"
"util.py" = ["4", "10-22"]

[cosmic-ray.distributor]
name = "local"